### ISSUE TITLE
Warning On Load

### ISSUE THREAD

**Issue by frankenzombies** [SineSwiper/RimWorld-AutoJobTitles#1]
[HugsLib][warn] Missing enum setting labels for enum AutoJobTitles.ChangeJobTitlePriority
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
HugsLib.Utils.ModLogger:Warning (string,object[])
HugsLib.Settings.ModSettingsPack:GetHandle<AutoJobTitles.ChangeJobTitlePriority> (string,string,string,AutoJobTitles.ChangeJobTitlePriority,HugsLib.Settings.SettingHandle/ValueIsValid,string)
AutoJobTitles.Base:ProcessSettings ()
AutoJobTitles.Base:DefsLoaded ()
HugsLib.HugsLibController:OnDefsLoaded ()
HugsLib.HugsLibController:LoadReloadInitialize ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by SineSwiper** [comment]
This was fixed with the v1.4 update.
